GET http://localhost:3000/posts
Authorization: Bearer {token}

### get new access token
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "{token}"
}

### Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "chen"
}

### Logout
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "{token}"
}
